### ISSUE TITLE
Could not run bundle install from freshly cloned repo. "Could not find rubocop-rails-0.4.1 in any of the sources"

### ISSUE THREAD

**Issue by rprandi** [howtographql/graphql-ruby#13]
Hello,

Just writing to let you know that i tried to clone the project and make it run but was running on this error (Could not find rubocop-rails-0.4.1 in any of the sources) and i solved it by deleting the Gemfile.lock and running bundle install again.  

I am running ruby 2.4.1 and rails 5.1.6.

**Comment by RStankov** [comment]
This gem was renamed. I update the bundle, so everything should be working now. Thanks for reporting.
