### ISSUE TITLE
Filtering doesn't appear to work as expected

### ISSUE THREAD

**Issue by AlanFoster** [howtographql/graphql-ruby#18]
Hey, this might be a failure on my part - but from reading the guide on filtering with graphql https://www.howtographql.com/graphql-ruby/7-filtering/ the following screenshot is used:

![image](https://user-images.githubusercontent.com/1271782/51759742-d02e0f80-20c0-11e9-909b-54c0f8e16c1a.png)

But if I clone this repository, and apply the fix from https://github.com/howtographql/graphql-ruby/pull/17, and run the same query I get:

![image](https://user-images.githubusercontent.com/1271782/51759820-fce22700-20c0-11e9-9a63-698da7a2b288.png)

I would have expected no links to be returned, as none of the descriptions contain `example`.
Any help would be appreciated :+1:

**Comment by AlanFoster** [comment]
@RStankov Thanks for the quick response! Filtering still doesn't work as expected for me unfortunately - for visibility, which commit fixes the filtering?

**Comment by RStankov** [comment]
This commit fixes it: https://github.com/howtographql/graphql-ruby/commit/1b902a25d94b8d34f43043d6aa27f6512d27f023

`description_contains` have to be `descriptionContains'

**Comment by AlanFoster** [comment]
@RStankov that was my commit - it wasn't a fix for this logical bug though :(

**Comment by AlanFoster** [comment]
The first screenshot is from the guide, and the second screenshot was from master that used `descriptionContains` - but it didn't return the right results
