### ISSUE TITLE
DateTimeType undefined

### ISSUE THREAD

**Issue by ConorSheehan1** [howtographql/graphql-ruby#20]
Related to https://github.com/rmosolgo/graphiql-rails/issues/29

In https://www.howtographql.com/graphql-ruby/2-queries/ `DateTimeType` is used in `
app/graphql/types/link_type.rb` but it's not defined yet.

The result is that when you open `http://localhost:3000/graphiql` you get
```
SyntaxError: Unexpected token < in JSON at position 0
```
![graphql_error](https://user-images.githubusercontent.com/16896053/52337428-85d15a80-29ff-11e9-9f47-d9e3307c612d.png)

I [got around the issue](https://github.com/rmosolgo/graphiql-rails/issues/29#issuecomment-460981832) by copying [date_time_type.rb](https://github.com/howtographql/graphql-ruby/blob/347d02c7a06e68c395b613bdf1e09839ee493a2d/app/graphql/types/date_time_type.rb#L1) with a minor adjustment to inherit from `GraphQL::Schema::Scalar` instead of `BaseScalar`

Maybe the step to add date_time_type could be added to the tutorial?
Or a default type available in graphql 1.8.13 could be used instead?

Thanks for the great tutorial!

**Comment by RStankov** [comment]
Will check, thanks for reporing

**Comment by RStankov** [comment]
Hey, I opened a PR which fixes this issue 👉 https://github.com/howtographql/howtographql/pull/897

**Comment by jonatasbaldin** [comment]
Fixed at #897.

**Comment by jonatasbaldin** [comment]
hey @RStankov, you may close this one ;)
