### ISSUE TITLE
Test Failure: Resolvers::LinksSearchTest#test_filter_option [/test/graphql/resolvers/links_search_test.rb:42]

### ISSUE THREAD

**Issue by billfienberg** [howtographql/graphql-ruby#23]
![image](https://user-images.githubusercontent.com/6130520/58764406-25c16f80-852c-11e9-99d7-c7e9ad75051c.png)

```
Failure:
Resolvers::LinksSearchTest#test_filter_option [/Users/bill/graphql-ruby/test/graphql/resolvers/links_search_test.rb:42]:
--- expected
+++ actual
@@ -1 +1 @@
-["test1", "test2", "test3", "test4"]
+["test1", "test2", "test3"]
```

**Comment by RStankov** [comment]
Fixed in master, thanks for reporting 🙌

**Comment by billfienberg** [comment]
> Fixed in master, thanks for reporting 🙌
> 
> [099c47e](https://github.com/howtographql/graphql-ruby/commit/099c47e8f162de95251527de63d9a55b3cc4abac)

You're welcome. Sorry I didn't have time to try to fix it myself.
