### ISSUE TITLE
Connecting with howtographql/react-apollo

### ISSUE THREAD

**Issue by tb** [howtographql/graphql-ruby#4]
I have configured howtographql/react-apollo with:

    const networkInterface = createNetworkInterface({
      uri: 'http://localhost:3000/graphql'
    })

I have removed the subscriptions, issue https://github.com/howtographql/graphql-ruby/issues/3

Anyway, to get the app to work I still had to do 2 things:
- add rack-cors - PR https://github.com/howtographql/graphql-ruby/pull/5 (alternative is to set proxy on create-react-app package.json)
- comment out protect_from_forgery (no idea how to fix it properly atm)

**Comment by RStankov** [comment]
I removed `protect_from_forgery` in a https://github.com/howtographql/graphql-ruby/pull/16
