### ISSUE TITLE
react-apollo AllLinksSearchQuery does not work

### ISSUE THREAD

**Issue by tb** [howtographql/graphql-ruby#6]
When connected via react-apollo (see https://github.com/howtographql/graphql-ruby/issues/4) I can login and see links but search is broken, I see error: `ApolloError.js:32 Uncaught (in promise) Error: GraphQL error: Variable searchText of type String! was provided invalid value`

I was able to reproduce it in graphiql with:
```graphql
query AllLinksSearchQuery($searchText: String!) {
  allLinks(filter: {
    OR: [
    	{url_contains: $searchText},
    	{description_contains: $searchText}
    ]
  }) {
    id
    url
    description
  }
}
```
and query variables:
```json
{
  "$searchText": "Link"
}
```

I get error:
```json
{
  "errors": [
    {
      "message": "Variable searchText of type String! was provided invalid value",
      "locations": [
        {
          "line": 1,
          "column": 27
        }
      ],
      "value": null,
      "problems": [
        {
          "path": [],
          "explanation": "Expected value to not be null"
        }
      ]
    }
  ]
}
```

**Comment by RStankov** [comment]
Variables should not contain `$`:

```
{
  "searchText": "Link"
}
```

This gets converted to `$searchText` variable in the query.
