### ISSUE TITLE
Graphql controller has incorrect variable name

### ISSUE THREAD

**Issue by nbarthel** [howtographql/graphql-ruby#8]
Maybe I'm missing something, but your Graphql controller has a bug in it.  I made the mistake of copying it directly and wondered why variables weren't working.

graphql-ruby/app/controllers/graphql_controller.rb

`  def variables
    ensure_hash params[:validates]
  end`

Shouldn't the param be ":variables"?

**Comment by RStankov** [comment]
You are correct. Will fix. Thanks for noticing.
